### ISSUE TITLE
go get fails because of hashicorp dependency

### ISSUE THREAD

**Issue by davewo** [ory/go-acc#25]
Not sure if this is a temporary misconfiguration of the HCL repo, but `go-acc` may want to point at a specific tag for the `hcl` module.

```
Daves-MacBook-Pro:go dave$ go get github.com/ory/go-acc
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/Users/dave/.gvm/gos/go1.14.9/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/Users/dave/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```

**Comment by ritikasharma20** [comment]
Am facing the same issue, was wondering if this is temporary or is there any workaround?

**Comment by jakesyl** [comment]
I'm having the same issue

**Comment by jakesyl** [comment]
Okay, found a workaround. I think my github actions bumped go or something and you upgraded your version or something. You have to turn on `GO111MODULE`. Here's the config:

```
  - name: Install go-acc
    shell: bash
    run: go get -u github.com/ory/go-acc
    env:
      GO111MODULE: "on"
```
